HOTFIX: fix subscription narrowing problem
microsoft/graphitation pull request #306
Opened 2023-05-11 08:44 UTC by vejrj

2023-05-11 08:58 UTC, alloy commented on packages/ts-codegen/src/__tests__/index.test.ts
>                  subscribe: (model: unknown, args: {}, context: unknown, info: ResolveInfo) => PromiseOrValue<AsyncIterator<{
These comments seem unnecessary, just have the commit/PR have a good description of the problem.

2023-05-11 09:00 UTC, alloy reviewed
I’m missing an example of what the resolver implementation would look like. Is this requiring folks to include the kind property in their implementation?

2023-05-11 09:28 UTC, vejrj commented
> I’m missing an example of what the resolver implementation would look like. Is this requiring folks to include the kind property in their implementation?

Yes, you will need to add kind for "SubscribeAndResolve"

2023-05-11 09:31 UTC, alloy commented
That doesn’t seem helpful. At that point it’s more intuitive to export two different type definitions.

2023-05-11 09:34 UTC, vejrj commented
> That doesn’t seem helpful. At that point it’s more intuitive to export two different type definitions.

That was my initial idea, but @freiksenet said that we would need to refactor everything then.

2023-05-11 09:39 UTC, alloy commented
Can you elaborate on the difference in effort needed to add `kind` vs using a different type? Both can be done relatively the same way with a codemod afaik.

2023-05-15 10:16 UTC, alloy requested changes
As discussed offline, I consider this solution a no-go. We provide framework solutions and we need to consider our customers [the product engineers], and this workaround is not intuitive. We should:

1. Figure out if it's simply not possible to provide a single type and have TypeScript correctly narrow the union;
2. and otherwise provide 2 types and have the product engineer choose the right one—which is something that they can intuitively understand.

2024-05-15 12:04 UTC, closed without merging